insert into DATA_ELEMENTS values ("DE002",0,19);
insert into DATA_ELEMENTS values ("DE003",1,2);
insert into DATA_ELEMENTS values ("DE003",2,2);
insert into DATA_ELEMENTS values ("DE003",3,2);
insert into DATA_ELEMENTS values ("DE004",0,12);
insert into DATA_ELEMENTS values ("DE005",0,12);
insert into DATA_ELEMENTS values ("DE006",0,12);
insert into DATA_ELEMENTS values ("DE007",null, null);
insert into DATA_ELEMENTS values ("DE008",null, null);
insert into DATA_ELEMENTS values ("DE009",0,8);
insert into DATA_ELEMENTS values ("DE010",0,8);
insert into DATA_ELEMENTS values ("DE011",null, null);
insert into DATA_ELEMENTS values ("DE012",1,6);
insert into DATA_ELEMENTS values ("DE012",2,6);
insert into DATA_ELEMENTS values ("DE013",null, null);
insert into DATA_ELEMENTS values ("DE014",0,4);
insert into DATA_ELEMENTS values ("DE015",null, null);
insert into DATA_ELEMENTS values ("DE016",null, null);
insert into DATA_ELEMENTS values ("DE017",null, null);
insert into DATA_ELEMENTS values ("DE018",null, null);
insert into DATA_ELEMENTS values ("DE019",null, null);
insert into DATA_ELEMENTS values ("DE020",null, null);
insert into DATA_ELEMENTS values ("DE021",null, null);
insert into DATA_ELEMENTS values ("DE022",1,1);
insert into DATA_ELEMENTS values ("DE022",2,1);
insert into DATA_ELEMENTS values ("DE022",3,1);
insert into DATA_ELEMENTS values ("DE022",4,1);
insert into DATA_ELEMENTS values ("DE022",5,1);
insert into DATA_ELEMENTS values ("DE022",6,1);
insert into DATA_ELEMENTS values ("DE022",7,1);
insert into DATA_ELEMENTS values ("DE022",8,1);
insert into DATA_ELEMENTS values ("DE022",9,1);
insert into DATA_ELEMENTS values ("DE022",10,1);
insert into DATA_ELEMENTS values ("DE022",11,1);
insert into DATA_ELEMENTS values ("DE022",12,1);
insert into DATA_ELEMENTS values ("DE023",0,3);
insert into DATA_ELEMENTS values ("DE024",0,3);
insert into DATA_ELEMENTS values ("DE025",0,4);
insert into DATA_ELEMENTS values ("DE026",0,4);
insert into DATA_ELEMENTS values ("DE027",null, null);
insert into DATA_ELEMENTS values ("DE028",null, null);
insert into DATA_ELEMENTS values ("DE029",null, null);
insert into DATA_ELEMENTS values ("DE030",1,12);
insert into DATA_ELEMENTS values ("DE030",2,12);
insert into DATA_ELEMENTS values ("DE031",1,1);
insert into DATA_ELEMENTS values ("DE031",2,6);
insert into DATA_ELEMENTS values ("DE031",3,4);
insert into DATA_ELEMENTS values ("DE031",4,11);
insert into DATA_ELEMENTS values ("DE031",5,1);
insert into DATA_ELEMENTS values ("DE032",0,11);
insert into DATA_ELEMENTS values ("DE033",0,11);
insert into DATA_ELEMENTS values ("DE034",null, null);
insert into DATA_ELEMENTS values ("DE035",null, null);
insert into DATA_ELEMENTS values ("DE036",null, null);
insert into DATA_ELEMENTS values ("DE037",0,12);
insert into DATA_ELEMENTS values ("DE038",0,6);
insert into DATA_ELEMENTS values ("DE039",null, null);
insert into DATA_ELEMENTS values ("DE040",0,3);
insert into DATA_ELEMENTS values ("DE041",0,8);
insert into DATA_ELEMENTS values ("DE042",0,15);
insert into DATA_ELEMENTS values ("DE043",1,22);
insert into DATA_ELEMENTS values ("DE043",2,48);
insert into DATA_ELEMENTS values ("DE043",3,13);
insert into DATA_ELEMENTS values ("DE043",4,10);
insert into DATA_ELEMENTS values ("DE043",5,3);
insert into DATA_ELEMENTS values ("DE043",6,3);
insert into DATA_ELEMENTS values ("DE044",null, null);
insert into DATA_ELEMENTS values ("DE045",null, null);
insert into DATA_ELEMENTS values ("DE046",null, null);
insert into DATA_ELEMENTS values ("DE047",null, null);
insert into DATA_ELEMENTS values ("DE048",0,999);
insert into DATA_ELEMENTS values ("DE049",0,3);
insert into DATA_ELEMENTS values ("DE050",0,3);
insert into DATA_ELEMENTS values ("DE051",0,3);
insert into DATA_ELEMENTS values ("DE052",null, null);
insert into DATA_ELEMENTS values ("DE053",null, null);
insert into DATA_ELEMENTS values ("DE054",1,2);
insert into DATA_ELEMENTS values ("DE054",2,2);
insert into DATA_ELEMENTS values ("DE054",3,3);
insert into DATA_ELEMENTS values ("DE054",4,1);
insert into DATA_ELEMENTS values ("DE054",5,12);
insert into DATA_ELEMENTS values ("DE055",0,255);
insert into DATA_ELEMENTS values ("DE056",null, null);
insert into DATA_ELEMENTS values ("DE057",null, null);
insert into DATA_ELEMENTS values ("DE058",null, null);
insert into DATA_ELEMENTS values ("DE059",null, null);
insert into DATA_ELEMENTS values ("DE060",null, null);
insert into DATA_ELEMENTS values ("DE061",null, null);
insert into DATA_ELEMENTS values ("DE062",0,999);
insert into DATA_ELEMENTS values ("DE063",1,1);
insert into DATA_ELEMENTS values ("DE063",2,15);
insert into DATA_ELEMENTS values ("DE064",null, null);
insert into DATA_ELEMENTS values ("DE065",null, null);
insert into DATA_ELEMENTS values ("DE066",null, null);
insert into DATA_ELEMENTS values ("DE067",null, null);
insert into DATA_ELEMENTS values ("DE068",null, null);
insert into DATA_ELEMENTS values ("DE069",null, null);
insert into DATA_ELEMENTS values ("DE070",null, null);
insert into DATA_ELEMENTS values ("DE071",0,8);
insert into DATA_ELEMENTS values ("DE072",0,999);
insert into DATA_ELEMENTS values ("DE073",0,6);
insert into DATA_ELEMENTS values ("DE074",null, null);
insert into DATA_ELEMENTS values ("DE075",null, null);
insert into DATA_ELEMENTS values ("DE076",null, null);
insert into DATA_ELEMENTS values ("DE077",null, null);
insert into DATA_ELEMENTS values ("DE078",null, null);
insert into DATA_ELEMENTS values ("DE079",null, null);
insert into DATA_ELEMENTS values ("DE080",null, null);
insert into DATA_ELEMENTS values ("DE081",null, null);
insert into DATA_ELEMENTS values ("DE082",null, null);
insert into DATA_ELEMENTS values ("DE083",null, null);
insert into DATA_ELEMENTS values ("DE084",null, null);
insert into DATA_ELEMENTS values ("DE085",null, null);
insert into DATA_ELEMENTS values ("DE086",null, null);
insert into DATA_ELEMENTS values ("DE087",null, null);
insert into DATA_ELEMENTS values ("DE088",null, null);
insert into DATA_ELEMENTS values ("DE089",null, null);
insert into DATA_ELEMENTS values ("DE090",null, null);
insert into DATA_ELEMENTS values ("DE091",null, null);
insert into DATA_ELEMENTS values ("DE092",null, null);
insert into DATA_ELEMENTS values ("DE093",0,11);
insert into DATA_ELEMENTS values ("DE094",0,11);
insert into DATA_ELEMENTS values ("DE095",0,10);
insert into DATA_ELEMENTS values ("DE096",null, null);
insert into DATA_ELEMENTS values ("DE097",null, null);
insert into DATA_ELEMENTS values ("DE098",null, null);
insert into DATA_ELEMENTS values ("DE099",null, null);
insert into DATA_ELEMENTS values ("DE100",0,11);
insert into DATA_ELEMENTS values ("DE101",null, null);
insert into DATA_ELEMENTS values ("DE102",null, null);
insert into DATA_ELEMENTS values ("DE103",null, null);
insert into DATA_ELEMENTS values ("DE104",null, null);
insert into DATA_ELEMENTS values ("DE105",null, null);
insert into DATA_ELEMENTS values ("DE106",null, null);
insert into DATA_ELEMENTS values ("DE107",null, null);
insert into DATA_ELEMENTS values ("DE108",null, null);
insert into DATA_ELEMENTS values ("DE109",null, null);
insert into DATA_ELEMENTS values ("DE110",null, null);
insert into DATA_ELEMENTS values ("DE111",0,12);
insert into DATA_ELEMENTS values ("DE112",null, null);
insert into DATA_ELEMENTS values ("DE113",null, null);
insert into DATA_ELEMENTS values ("DE114",null, null);
insert into DATA_ELEMENTS values ("DE115",null, null);
insert into DATA_ELEMENTS values ("DE116",null, null);
insert into DATA_ELEMENTS values ("DE117",null, null);
insert into DATA_ELEMENTS values ("DE118",null, null);
insert into DATA_ELEMENTS values ("DE119",null, null);
insert into DATA_ELEMENTS values ("DE120",null, null);
insert into DATA_ELEMENTS values ("DE121",null, null);
insert into DATA_ELEMENTS values ("DE122",null, null);
insert into DATA_ELEMENTS values ("DE123",0,999);
insert into DATA_ELEMENTS values ("DE124",0,999);
insert into DATA_ELEMENTS values ("DE125",0,999);
insert into DATA_ELEMENTS values ("DE126",null, null);
insert into DATA_ELEMENTS values ("DE127",0,999);
insert into DATA_ELEMENTS values ("DE128",null, null);
